import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import SearchInput from "../components/SearchInput";
import IconItem from "../components/IconItem";
import MenuItem from "../components/MenuItem";
import RectBanner from "../components/RectBanner";
import SquareImage from "../components/SquareImage";
import ProductCard from "../components/ProductCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Flex Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main" id="flex-1">
        <div className="header-nav">
          <div className="container" id="flex-2">
            <div id="flex-3">
              <Image src={"/logo.svg"} width={36} height={36} alt={"logo"} />
              <nav>
                <MenuItem label="All" />
                <MenuItem label="Apparel" />
                <MenuItem label="Gadget" />
              </nav>
              <div className={"icon-menu"}>
                <IconItem icon="menu" />
              </div>
            </div>
            <SearchInput />
            <div id="flex-4">
              <IconItem icon="bag" />
              <IconItem icon="user" />
            </div>
          </div>
        </div>

        <div className="banner-gallery" id="flex-5">
          <RectBanner size="large" />
          <SquareImage size="small" />
          <SquareImage size="small" />
          <SquareImage size="medium" />
          <SquareImage size="small" />
          <SquareImage size="small" />
        </div>
        <h1 className="heading">Products</h1>
        <div className="product-list" id="flex-6">
          {Array.from(Array(10).keys()).map((e, i) => (
            <ProductCard key={i} />
          ))}
        </div>
        <div className="text-combo" id="flex-7">
          <div className="paragraph-box" id="flex-8">
            <h1 className="heading">Best Seller</h1>
            <p className="paragraph">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
              lobortis pharetra metus, sed imperdiet libero elementum ac.
              Vestibulum egestas commodo arcu, id viverra nisi egestas quis.
              Nulla vel lorem in mauris molestie congue id a risus. Cras commodo
              arcu in libero consectetur faucibus. Curabitur ligula risus,
              varius a ante quis, vulputate porttitor est.
            </p>
            <button>See More</button>
          </div>
          <SquareImage size="large" />
        </div>
        <div className="promotion-banner">
          <div className={"promotion-banner-left"} id={"flex-9"}>
            <RectBanner size="small" autoWidth />
            <RectBanner size="small" autoWidth />
          </div>
          <div className={"promotion-banner-right"} id={"flex-10"}>
            <RectBanner size="medium" autoWidth />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
